### ISSUE TITLE
[Feature Request] Support stickers

### ISSUE THREAD

**Issue by Ayfri** [powerfart-plugins/image-tools#18]
**Describe the feature request**
Have Image Tools drop down menu on stickers.

**Expected behavior**
Be able to `save`, `download` and if possible `copy` & `copy link` of stickers.

**Comment by userXinos** [comment]
well, at least it works with custom stickers (from the server)

**Comment by userXinos** [comment]
Unfortunately, I can open and save (json...) only due to the very specific [technology] (https://lottiefiles.com/) in naive stickers (I can probably change the link so that I can open it like a normal image, but only in the browser)
