### ISSUE TITLE
[Feature Request] Have a save button in the drop down menu for videos

### ISSUE THREAD

**Issue by Dan3a** [powerfart-plugins/image-tools#20]
**Describe the feature request**
Have the same save options as images but for videos, like on ImageUtilities on BetterDiscord.

**Expected behavior**
Have a "Video" button like the "Image" button when right clicking on videos, containing options such as "Save video", and "Save video As...". Save thing goes for videos embeded via links.

**Comment by userXinos** [comment]
although it is not difficult (in theory, probably), I do not think that this is the correct vector for a plugin centered on images
