### ISSUE TITLE
[Bug] right clicking on profile while in a voice chat crashed the client (since  5d13037)

### ISSUE THREAD

**Issue by Giotje** [powerfart-plugins/image-tools#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

this is the error in the console:
![image](https://user-images.githubusercontent.com/42942538/149159860-f411731a-fd0b-4ff8-a3b7-0d086f7877ee.png)

if u give me 30 minutes i'll open a PR with a bug fix

**Comment by userXinos** [comment]
ah, I didn't expect that there might be empty, I will push it with the next commit with other small fixes
