### ISSUE TITLE
[CHAT] Untrused?

### ISSUE THREAD

**Issue by xamionex** [powerfart-plugins/image-tools#25]
I Just read this In the Powercord discord and am wondering why are you untrusted?

> PSA: Uninstall plugins by "Xinos"
> After a regrettable lack of collaboration from this user regarding guidelines compliance despite our attempt at reaching out, as well as a very questionable and unhelpful behavior in the server, we unpublished all plugins from this developer and consider them untrusted (making their plugins "unsafe" to our eyes). We strongly recommend uninstalling plugins from them (or to be very cautious with future updates), for your safety. Posting or encouraging installing plugins from them will fall under rule 9.
> 
> This is not the first time we take such actions. Last time such actions were taken it was against Hellbound, and in case you don't know what happened following our actions, you can visit postmortem.
> 
> Look for your plugins folder and delete the following plugins: fix-unread-channels, hot-remount, chat-settings, my-palette, image-tools

**Comment by userXinos** [comment]
I don't trust myself
