### ISSUE TITLE
[Bug] No zoomed in image

### ISSUE THREAD

**Issue by romangraef** [powerfart-plugins/image-tools#26]
**Describe the bug**
Lens only blurs the background and show the lens border, but not the actual zoomed in picture.

**To Reproduce**
Leftclick on a picture popout

**Expected behavior**
A zoomed in version of the picture appears within the lens.

Whenever i open an image popout, i get a CORS error: 
```
Access to fetch at 'https://media.discordapp.net/attachments/XXXXXX/XXXXX/unknown.png?width=1172&height=201' from origin 'https://canary.discord.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by userXinos** [comment]
I can not reproduce, everything works fine. I haven't used direct image loading for a lens for a long time... I literally copy the image layer to use in the lens.

*url with your image looks very strange*

**Comment by romangraef** [comment]
maybe another plugin is interfering, will try in a clean instance of powercord

**Comment by romangraef** [comment]
Cannot reproduce in a clean instance without other plugins, closing this ig
