### ISSUE TITLE
context menu issue

### ISSUE THREAD

**Issue by kekkodance** [powerfart-plugins/image-tools#27]
started happening recently after a discord update which broke other plugins too 
![image](https://user-images.githubusercontent.com/53054786/167015874-d6a5941c-3f86-4dba-bf33-4d8e52b3f60f.png)

**Comment by xBiei** [comment]
I'll work on it when I'm free.
probably the next few days.

**Comment by userXinos** [comment]
@xBiei thank you very much, i sold the push which probably fixes it

**Comment by userXinos** [comment]
For the future of everyone else, I'm tired of supporting this shit, maybe this is the last update

**Comment by kekkodance** [comment]
this also started to happen recently on right click of any user's profile:
```js
Error: Failed to patch image-tools-guild-channel-user-context-menu; module is invalid.
    at inject (kernel://K:\Downloads\packages\pc-compat/dist/renderer.js:1:61274)
    at inject2 (K:\\Downloads\\powercord\\plugins\\image-tools\\utils\\inject2.js:26:3)
    at General.injectWithSettings (K:\\Downloads\\powercord\\plugins\\image-tools\\modules\\Patcher\\General.js:368:16)
    at eval (K:\\Downloads\\powercord\\plugins\\image-tools\\modules\\Patcher\\General.js:87:22)
    at https://discord.com/assets/0eb297585b87bfddc0a2.js:757:158
    at t.n.render (https://discord.com/assets/0eb297585b87bfddc0a2.js:3553:703)
    at qa (https://discord.com/assets/0eb297585b87bfddc0a2.js:5886:489)
    at Xa (https://discord.com/assets/0eb297585b87bfddc0a2.js:5886:288)
    at $s (https://discord.com/assets/0eb297585b87bfddc0a2.js:5926:166)
    at ku (https://discord.com/assets/0eb297585b87bfddc0a2.js:5916:748)```

**Comment by xBiei** [comment]
> this also started to happen recently on right click of any user's profile:
> 
> ```js
> 
> Error: Failed to patch image-tools-guild-channel-user-context-menu; module is invalid.
> 
>     at inject (kernel://K:\Downloads\packages\pc-compat/dist/renderer.js:1:61274)
> 
>     at inject2 (K:\\Downloads\\powercord\\plugins\\image-tools\\utils\\inject2.js:26:3)
> 
>     at General.injectWithSettings (K:\\Downloads\\powercord\\plugins\\image-tools\\modules\\Patcher\\General.js:368:16)
> 
>     at eval (K:\\Downloads\\powercord\\plugins\\image-tools\\modules\\Patcher\\General.js:87:22)
> 
>     at https://discord.com/assets/0eb297585b87bfddc0a2.js:757:158
> 
>     at t.n.render (https://discord.com/assets/0eb297585b87bfddc0a2.js:3553:703)
> 
>     at qa (https://discord.com/assets/0eb297585b87bfddc0a2.js:5886:489)
> 
>     at Xa (https://discord.com/assets/0eb297585b87bfddc0a2.js:5886:288)
> 
>     at $s (https://discord.com/assets/0eb297585b87bfddc0a2.js:5926:166)
> 
>     at ku (https://discord.com/assets/0eb297585b87bfddc0a2.js:5916:748)```

Yeah that's due to the new discord changes to some context menus

**Comment by kekkodance** [comment]
the issue still hasn't been fixed it seems

**Comment by Mertcan213** [comment]
oh it's still happening to me after updating is there any way that i can resolve this issue this is what i see on my dev console 
![image](https://user-images.githubusercontent.com/59136084/177880408-8872fc34-f024-4af1-9efa-497b8f5ad34e.png)

**Comment by Mertcan213** [comment]
> looks like the issue persists even after the fix. I'll check what's the problem.

oh thanks!

**Comment by xBiei** [comment]
I guess it's time to switch to the new context menu injection instead of this one.
it needs some refactoring so it'll take some time cuz I'm not entirely free.
unless xinos is gonna work on it.
if you urgently need this you can use lighty's using bdcompat.
