### ISSUE TITLE
Clicking an image crashes Discord

### ISSUE THREAD

**Issue by ThatOneKitsune** [powerfart-plugins/image-tools#31]
**Describe the bug**
Whenever I click an image, it will immediately crash Discord.

**To Reproduce**
Have Image Tools Enabled
Click any image

**Expected behavior**
Image pops up in bigger view

[console errors.log](https://github.com/powerfart-plugins/image-tools/files/9097193/console.errors.log)

**Comment by IveMalfunctioned** [comment]
Same issue here. Please fix ASAP

**Comment by xBiei** [comment]
https://github.com/powerfart-plugins/image-tools/issues/27#issuecomment-1178364913

**Comment by ThatOneKitsune** [comment]
> https://github.com/powerfart-plugins/image-tools/issues/27#issuecomment-1178364913

that was two months ago
